export const countyList = [
    { id: 'al-bcso', state: 'Alabama', county: 'Baldwin County' },
    { id: 'al-ccso', state: 'Alabama', county: 'Calhoun County' },
    { id: 'al-ccj', state: 'Alabama', county: 'Chambers County' },
    { id: 'al-chso', state: 'Alabama', county: 'Cherokee County' },
    { id: 'al-ccsd', state: 'Alabama', county: 'Coffee Co' },
    { id: 'al-colb', state: 'Alabama', county: 'Colbert County' },
    { id: 'al-coso', state: 'Alabama', county: 'Coosa County' },
    { id: 'al-dale', state: 'Alabama', county: 'Dale County' },
    { id: 'al-dcso', state: 'Alabama', county: 'DeKalb County' },
    { id: 'al-ecsd', state: 'Alabama', county: 'Elmore Co' },
    { id: 'al-ecso', state: 'Alabama', county: 'Etowah County' },
    { id: 'al-fcso', state: 'Alabama', county: 'Fayette County' },
    { id: 'al-fran', state: 'Alabama', county: 'Franklin County' },
    { id: 'al-jack', state: 'Alabama', county: 'Jackson County' },
    { id: 'al-jcso', state: 'Alabama', county: 'Jefferson County' },
    { id: 'al-mcsd', state: 'Alabama', county: 'Madison County' },
    { id: 'al-mari', state: 'Alabama', county: 'Marion County' },
    { id: 'al-mlso', state: 'Alabama', county: 'Marshall County' },
    { id: 'al-mcso', state: 'Alabama', county: 'Mobile County' },
    { id: 'al-myso', state: 'Alabama', county: 'Montgomery County' },
    { id: 'al-mnso', state: 'Alabama', county: 'Morgan County' },
    { id: 'al-pcso', state: 'Alabama', county: 'Pickens County' },
    { id: 'al-pike', state: 'Alabama', county: 'Pike County' },
    { id: 'al-scso', state: 'Alabama', county: 'Shelby County' },
    { id: 'al-tpd', state: 'Alabama', county: 'Trussville' },
    { id: 'al-tcso', state: 'Alabama', county: 'Tuscaloosa County' },
    { id: 'ak-apd', state: 'Alaska', county: 'Anchorage' },
    { id: 'az-ccso', state: 'Arizona', county: 'Cochise County' },
    { id: 'az-mcso', state: 'Arizona', county: 'Maricopa County' },
    { id: 'az-meso', state: 'Arizona', county: 'Mohave County' },
    { id: 'az-ncso', state: 'Arizona', county: 'Navajo County' },
    { id: 'az-pcso', state: 'Arizona', county: 'Pima County' },
    { id: 'az-plso', state: 'Arizona', county: 'Pinal County' },
    { id: 'az-spd', state: 'Arizona', county: 'Scottsdale' },
    { id: 'az-ycso', state: 'Arizonaavapai', county: 'County' },
    { id: 'az-yuma', state: 'Arizonauma', county: 'County' },
    { id: 'ar-acso', state: 'Arkansas', county: 'Arkansas Co' },
    { id: 'ar-bcso', state: 'Arkansas', county: 'Baxter County' },
    { id: 'ar-bnso', state: 'Arkansas', county: 'Benton County' },
    { id: 'ar-beso', state: 'Arkansas', county: 'Boone County' },
    { id: 'ar-cbd', state: 'Arkansas', county: 'Cabot' },
    { id: 'ar-chso', state: 'Arkansas', county: 'Calhoun Co' },
    { id: 'ar-cpd', state: 'Arkansas', county: 'Carlisle' },
    { id: 'ar-clcj', state: 'Arkansas', county: 'Carroll County' },
    { id: 'ar-ckso', state: 'Arkansas', county: 'Clark County' },
    { id: 'ar-cyso', state: 'Arkansas', county: 'Clay Co' },
    { id: 'ar-cbcj', state: 'Arkansas', county: 'Cleburne County' },
    { id: 'ar-clso', state: 'Arkansas', county: 'Cleveland Co' },
    { id: 'ar-cbso', state: 'Arkansas', county: 'Columbia County' }, 
    { id: 'ar-cycj', state: 'Arkansas', county: 'Conway County' },
    { id: 'ar-ccsd', state: 'Arkansas', county: 'Crawford Co' },
    { id: 'ar-crit', state: 'Arkansas', county: 'Crittenden County' },
    { id: 'ar-ccso', state: 'Arkansas', county: 'Cross County' },
    { id: 'ar-crd', state: 'Arkansas', county: 'Crossett' },
    { id: 'ar-dcso', state: 'Arkansas', county: 'Drew Co' },
    { id: 'ar-dcj', state: 'Arkansas', county: 'Dumas City' },
    { id: 'ar-epd', state: 'Arkansas', county: 'England' },
    { id: 'ar-facj', state: 'Arkansas', county: 'Faulkner County' },
    { id: 'ar-fncj', state: 'Arkansas', county: 'Franklin County' },
    { id: 'ar-fcso', state: 'Arkansas', county: 'Fulton Co' },
    { id: 'ar-gcso', state: 'Arkansas', county: 'Garland County' },
    { id: 'ar-gtso', state: 'Arkansas', county: 'Grant Co' },
    { id: 'ar-grso', state: 'Arkansas', county: 'Greene Co' },
    { id: 'ar-hecj', state: 'Arkansas', county: 'Hempstead County' },
    { id: 'ar-hscso', state: 'Arkansas', county: 'Hot Spring County' },
    { id: 'ar-hcso', state: 'Arkansas', county: 'Howard County' },
    { id: 'ar-icsd', state: 'Arkansas', county: 'Independence Co' },
    { id: 'ar-icso', state: 'Arkansas', county: 'Izard Co' },
    { id: 'ar-jkso', state: 'Arkansas', county: 'Jackson County' },
    { id: 'ar-jnso', state: 'Arkansas', county: 'Jefferson County' },
    { id: 'ar-jcso', state: 'Arkansas', county: 'Johnson County' },
    { id: 'ar-lwcj', state: 'Arkansas', county: 'Lawrence County' },
    { id: 'ar-leec', state: 'Arkansas', county: 'Lee County' },
    { id: 'ar-lcsd', state: 'Arkansas', county: 'Lincoln Co' },
    { id: 'ar-lrcso', state: 'Arkansas', county: 'Little River Co' },
    { id: 'ar-lgcj', state: 'Arkansas', county: 'Logan County' },
    { id: 'ar-lpd', state: 'Arkansas', county: 'Lonoke' },
    { id: 'ar-mdcj', state: 'Arkansas', county: 'Madison County' },
    { id: 'ar-mcso', state: 'Arkansas', county: 'Marion County' },
    { id: 'ar-mpd', state: 'Arkansas', county: 'McGehee' },
    { id: 'ar-mlso', state: 'Arkansas', county: 'Miller County' },
    { id: 'ar-msso', state: 'Arkansas', county: 'Mississippi County' },
    { id: 'ar-mnso', state: 'Arkansas', county: 'Monroe Co' },
    { id: 'ar-mtso', state: 'Arkansas', county: 'Montgomery Co' },
    { id: 'ar-ncso', state: 'Arkansas', county: 'Newton Co' },
    { id: 'ar-opd', state: 'Arkansas', county: 'Osceola' },
    { id: 'ar-ocsd', state: 'Arkansas', county: 'Ouachita Co' },
    { id: 'ar-prso', state: 'Arkansas', county: 'Perry Co' },
    { id: 'ar-pocj', state: 'Arkansas', county: 'Poinsett County' },
    { id: 'ar-pcso', state: 'Arkansas', county: 'Pope Co' },
    { id: 'ar-pula', state: 'Arkansas', county: 'Pulaski County' },
    { id: 'ar-rcso', state: 'Arkansas', county: 'Randolph Co' },
    { id: 'ar-sacj', state: 'Arkansas', county: 'Saline County' },
    { id: 'ar-scso', state: 'Arkansas', county: 'Scott County' },
    { id: 'ar-scsd', state: 'Arkansas', county: 'Searcy Co' },
    { id: 'ar-sbstn', state: 'Arkansas', county: 'Sebastian County' },
    { id: 'ar-svso', state: 'Arkansas', county: 'Sevier Co' },
    { id: 'ar-shso', state: 'Arkansas', county: 'Sharp County' },
    { id: 'ar-sfso', state: 'Arkansas', county: 'St. Francis County' },
    { id: 'ar-stso', state: 'Arkansas', county: 'Stone County' },
    { id: 'ar-vbcso', state: 'Arkansas', county: 'Van Buren Co' },
    { id: 'ar-wacj', state: 'Arkansas', county: 'Washington County' },
    { id: 'ar-wash', state: 'Arkansas', county: 'Washington County' },
    { id: 'ar-wcsd', state: 'Arkansas', county: 'White Co' },
    { id: 'ar-wcso', state: 'Arkansas', county: 'Woodruff Co' },
    { id: 'ar-ycj', state: 'Arkansas', county: 'Arkansasell County #2' },
    { id: 'ca-acso', state: 'California', county: 'Alameda County' },
    { id: 'ca-fcso', state: 'California', county: 'Fresno County' },
    { id: 'ca-kcso', state: 'California', county: 'Kern Co' },
    { id: 'ca-king', state: 'California', county: 'Kings County' },
    { id: 'ca-lcso', state: 'California', county: 'Los Angeles County' },
    { id: 'ca-mend', state: 'California', county: 'Mendocino County' },
    { id: 'ca-mcso', state: 'California', county: 'Monterey Co' },
    { id: 'ca-ocsd', state: 'California', county: 'Orange County' },
    { id: 'ca-rcsd', state: 'California', county: 'Riverside County' },
    { id: 'ca-sber', state: 'California', county: 'San Bernardino County' },
    { id: 'ca-sdsd', state: 'California', county: 'San Diego County' },
    { id: 'ca-sfso', state: 'California', county: 'San Francisco County' },
    { id: 'ca-sjsd', state: 'California', county: 'San Joaquin Co' },
    { id: 'ca-slso', state: 'California', county: 'Solano County' },
    { id: 'ca-snso', state: 'California', county: 'Sonoma County' },
    { id: 'ca-scsd', state: 'California', county: 'Stanislaus County' },
    { id: 'ca-tcso', state: 'California', county: 'Tulare County' },
    { id: 'ca-vcso', state: 'California', county: 'Ventura County' },
    { id: 'co-adms', state: 'Colorado', county: 'Adams County' },
    { id: 'co-acg', state: 'Colorado', county: 'Arapahoe County Government' },
    { id: 'co-acso', state: 'Colorado', county: 'Archuleta County' },
    { id: 'co-bcso', state: 'Colorado', county: 'Bent County' },
    { id: 'co-cccso', state: 'Colorado', county: 'Clear Creek Co' },
    { id: 'co-ccso', state: 'Colorado', county: 'Conejos Co' },
    { id: 'co-csso', state: 'Colorado', county: 'Custer Co' },
    { id: 'co-dcso', state: 'Colorado', county: 'Douglas County' },
    { id: 'co-epco', state: 'Colorado', county: 'El Paso County' },
    { id: 'co-ecso', state: 'Colorado', county: 'Elbert County' },
    { id: 'co-fcso', state: 'Colorado', county: 'Fremont Co' },
    { id: 'co-gcso', state: 'Colorado', county: 'Garfield Co' },
    { id: 'co-glso', state: 'Colorado', county: 'Gilpin Co' },
    { id: 'co-grso', state: 'Colorado', county: 'Grand County' },
    { id: 'co-jcso', state: 'Colorado', county: 'Jefferson County' },
    { id: 'co-kccso', state: 'Colorado', county: 'Kit Carson County' },
    { id: 'co-lpso', state: 'Colorado', county: 'La Plata' },
    { id: 'co-lkso', state: 'Colorado', county: 'Lake County' },
    { id: 'co-lrso', state: 'Colorado', county: 'Larimer Co' },
    { id: 'co-lcso', state: 'Colorado', county: 'Lincoln Co' },
    { id: 'co-mcso', state: 'Colorado', county: 'Moffat County' },
    { id: 'co-mnso', state: 'Colorado', county: 'Montezuma Co' },
    { id: 'co-ocso', state: 'Colorado', county: 'Otero Co' },
    { id: 'co-pcsd', state: 'Colorado', county: 'Pitkin Co' },
    { id: 'co-pcso', state: 'Colorado', county: 'Pueblo Co' },
    { id: 'co-rcso', state: 'Colorado', county: 'Routt Co' },
    { id: 'co-ycsd', state: 'Colorado', county: 'Yuma Co' },
    { id: 'ct-cdc', state: 'Connecticut', county: 'Connecticut' },
    { id: 'fl-alac', state: 'Florida', county: 'Alachua County' },
    { id: 'fl-brad', state: 'Florida', county: 'Bradford County' },
    { id: 'fl-bcso', state: 'Florida', county: 'Brevard County' },
    { id: 'fl-bso', state: 'Florida', county: 'Broward' },
    { id: 'fl-chso', state: 'Florida', county: 'Charlotte Co' },
    { id: 'fl-coll', state: 'Florida', county: 'Collier County' },
    { id: 'fl-ccso', state: 'Florida', county: 'Columbia County' },
    { id: 'fl-dcso', state: 'Florida', county: 'Desoto County' },
    { id: 'fl-ecso', state: 'Florida', county: 'Escambia County' },
    { id: 'fl-flag', state: 'Florida', county: 'Flagler County' },
    { id: 'fl-fcso', state: 'Florida', county: 'Franklin Co' },
    { id: 'fl-gcso', state: 'Florida', county: 'Gadsden County' },
    { id: 'fl-giso', state: 'Florida', county: 'Gilchrist County' },
    { id: 'fl-glds', state: 'Florida', county: 'Glades County' },
    { id: 'fl-hmltn', state: 'Florida', county: 'Hamilton County' },
    { id: 'fl-hrso', state: 'Florida', county: 'Hardee County' },
    { id: 'fl-hndr', state: 'Florida', county: 'Hendry County' },
    { id: 'fl-hern', state: 'Florida', county: 'Hernando County' },
    { id: 'fl-hcso', state: 'Florida', county: 'Hillsborough County' },
    { id: 'fl-hlso', state: 'Florida', county: 'Holmes County' },
    { id: 'fl-jso', state: 'Florida', county: 'Jacksonville' },
    { id: 'fl-lake', state: 'Florida', county: 'Lake County' },
    { id: 'fl-lcso', state: 'Florida', county: 'Lee County' },
    { id: 'fl-levy', state: 'Florida', county: 'Levy County' },
    { id: 'fl-mana', state: 'Florida', county: 'Manatee County' },
    { id: 'fl-mcso', state: 'Florida', county: 'Marion County' },
    { id: 'fl-mart', state: 'Florida', county: 'Martin County' },
    { id: 'fl-mdc', state: 'Florida', county: 'Miami-Dade County Corrections' },
    { id: 'fl-monr', state: 'Florida', county: 'Monroe County' },
    { id: 'fl-ncso', state: 'Florida', county: 'Nassau County' },
    { id: 'fl-ocj', state: 'Florida', county: 'Okeechobee County' },
    { id: 'fl-occ', state: 'Florida', county: 'Orange County Corrections' },
    { id: 'fl-occd', state: 'Florida', county: 'Osceola County Corrections Department' },
    { id: 'fl-pbso', state: 'Florida', county: 'Palm Beach County' },
    { id: 'fl-pso', state: 'Florida', county: 'Pasco' },
    { id: 'fl-pcso', state: 'Florida', county: 'Pinellas County' },
    { id: 'fl-pkso', state: 'Florida', county: 'Polk County' },
    { id: 'fl-putn', state: 'Florida', county: 'Putnam County' },
    { id: 'fl-srcso', state: 'Florida', county: 'Santa Rosa County' },
    { id: 'fl-sara', state: 'Florida', county: 'Sarasota County' },
    { id: 'fl-sjcso', state: 'Florida', county: 'St. Johns County' },
    { id: 'fl-slcs', state: 'Florida', county: 'St. Lucie County' },
    { id: 'fl-smtr', state: 'Florida', county: 'Sumter County' },
    { id: 'fl-suwa', state: 'Florida', county: 'Suwannee County' },
    { id: 'fl-vcc', state: 'Florida', county: 'Volusia County Corrections' },
    { id: 'fl-wcso', state: 'Florida', county: 'Walton County' },
    { id: 'ga-ccso', state: 'Georgia', county: 'Chatham County' },
    { id: 'ga-cobb', state: 'Georgia', county: 'Cobb County Adultties' },
    { id: 'ga-colum', state: 'Georgia', county: 'Columbia County' },
    { id: 'ga-cwt', state: 'Georgia', county: 'Coweta County' },
    { id: 'ga-dcso', state: 'Georgia', county: 'Dawson County' },
    { id: 'ga-dgls', state: 'Georgia', county: 'Douglas County' },
    { id: 'ga-ftt', state: 'Georgia', county: 'Fayette County' },
    { id: 'ga-fld', state: 'Georgia', county: 'Floyd County' },
    { id: 'ga-fcso', state: 'Georgia', county: 'Fulton County' },
    { id: 'ga-gcsd', state: 'Georgia', county: 'Gwinnett County' },
    { id: 'ga-hcso', state: 'Georgia', county: 'Hall County' },
    { id: 'ga-lcso', state: 'Georgia', county: 'Lumpkin County' },
    { id: 'ga-ocso', state: 'Georgia', county: 'Oconee County' },
    { id: 'ga-pcso', state: 'Georgia', county: 'Paulding County' },
    { id: 'ga-walt', state: 'Georgia', county: 'Walton County' },
    { id: 'ga-whte', state: 'Georgia', county: 'White County' },
    { id: 'ga-wcso', state: 'Georgia', county: 'Whitfield County' },
    { id: 'id-acso', state: 'Idaho', county: 'Ada County' },
    { id: 'id-amso', state: 'Idaho', county: 'Adams Co' },
    { id: 'id-bann', state: 'Idaho', county: 'Bannock County' },
    { id: 'id-bnso', state: 'Idaho', county: 'Benewah County' },
    { id: 'id-bcso', state: 'Idaho', county: 'Bingham Co' },
    { id: 'id-blso', state: 'Idaho', county: 'Blaine County' },
    { id: 'id-btso', state: 'Idaho', county: 'Butte Co' },
    { id: 'id-cany', state: 'Idaho', county: 'Canyon County' },
    { id: 'id-ccso', state: 'Idaho', county: 'Cassia Co' },
    { id: 'id-ecso', state: 'Idaho', county: 'Elmore Co' },
    { id: 'id-fcso', state: 'Idaho', county: 'Fremont Co' },
    { id: 'id-gcso', state: 'Idaho', county: 'Gooding Co' },
    { id: 'id-jfso', state: 'Idaho', county: 'Jefferson Co' },
    { id: 'id-jcso', state: 'Idaho', county: 'Jerome County' },
    { id: 'id-lcso', state: 'Idaho', county: 'Lewis Co' },
    { id: 'id-mcso', state: 'Idaho', county: 'Madison County' },
    { id: 'id-ocso', state: 'Idaho', county: 'Owyhee Co' },
    { id: 'id-pyso', state: 'Idaho', county: 'Payette Co' },
    { id: 'id-pcso', state: 'Idaho', county: 'Power Co' },
    { id: 'id-scso', state: 'Idaho', county: 'Shoshone County' },
    { id: 'id-tfcso', state: 'Idaho', county: 'Twin Falls Co' },
    { id: 'id-vcso', state: 'Idaho', county: 'Valley Co' },
    { id: 'id-wcso', state: 'Idaho', county: 'Washington County' },
    { id: 'il-ccsd', state: 'Illinois', county: 'Clinton County' },
    { id: 'il-clso', state: 'Illinois', county: 'Coles Co' },
    { id: 'il-ccso', state: 'Illinois', county: 'Cook County' },
    { id: 'il-dcso', state: 'Illinois', county: 'DeKalb County' },
    { id: 'il-dupa', state: 'Illinois', county: 'Dupage County' },
    { id: 'il-gcsp', state: 'Illinois', county: "Grundy County Sheriff's Police" },
    { id: 'il-kcso', state: 'Illinois', county: 'Kane County' },
    { id: 'il-lcso', state: 'Illinois', county: 'Lake County' },
    { id: 'il-leso', state: 'Illinois', county: 'Lee Co' },
    { id: 'il-mcso', state: 'Illinois', county: 'McHenry Co' },
    { id: 'il-pcso', state: 'Illinois', county: 'Peoria County' },
    { id: 'il-tcso', state: 'Illinois', county: 'Tazewell County' },
    { id: 'il-will', state: 'Illinois', county: 'Will County' },
    { id: 'il-wcso', state: 'Illinois', county: 'Winnebago County' },
    { id: 'in-acso', state: 'Indiana', county: 'Allen County' },
    { id: 'in-bcso', state: 'Indiana', county: 'Boone County' },
    { id: 'in-brwn', state: 'Indiana', county: 'Brown County' },
    { id: 'in-clso', state: 'Indiana', county: 'Clark County' },
    { id: 'in-ccsd', state: 'Indiana', county: 'Clay County' },
    { id: 'in-ccso', state: 'Indiana', county: 'Crawford County' },
    { id: 'in-dcso', state: 'Indiana', county: 'Dearborn County' },
    { id: 'in-dKso', state: 'Indiana', county: 'DeKalb County' },
    { id: 'in-dela', state: 'Indiana', county: 'Delaware County' },
    { id: 'in-dbso', state: 'Indiana', county: 'Dubois County' },
    { id: 'in-gbcj', state: 'Indiana', county: 'Gibson County' },
    { id: 'in-hc', state: 'Indiana', county: 'Hamilton County' },
    { id: 'in-hcso', state: 'Indiana', county: 'Hancock County' },
    { id: 'in-hend', state: 'Indiana', county: 'Hendricks County' },
    { id: 'in-howa', state: 'Indiana', county: 'Howard County' },
    { id: 'in-jack', state: 'Indiana', county: 'Jackson County' },
    { id: 'in-jcso', state: 'Indiana', county: 'Jasper County' },
    { id: 'in-kcso', state: 'Indiana', county: 'Knox County' },
    { id: 'in-lpc', state: 'Indiana', county: 'La Porte County' },
    { id: 'in-mdsn', state: 'Indiana', county: 'Madison County' },
    { id: 'in-mcso', state: 'Indiana', county: 'Marion County' },
    { id: 'in-mmso', state: 'Indiana', county: 'Miami County' },
    { id: 'in-mont', state: 'Indiana', county: 'Montgomery County' },
    { id: 'in-ntcj', state: 'Indiana', county: 'Newton County' },
    { id: 'in-perr', state: 'Indiana', county: 'Perry County' },
    { id: 'in-pcso', state: 'Indiana', county: 'Pulaski County' },
    { id: 'in-putn', state: 'Indiana', county: 'Putnam County' },
    { id: 'in-rcso', state: 'Indiana', county: 'Ripley County' },
    { id: 'in-scot', state: 'Indiana', county: 'Scott County' },
    { id: 'in-scso', state: 'Indiana', county: 'Scott County' },
    { id: 'in-sjc', state: 'Indiana', county: 'St. Joseph County' },
    { id: 'in-strk', state: 'Indiana', county: 'Starke County' },
    { id: 'in-stso', state: 'Indiana', county: 'Steuben County' },
    { id: 'in-tcso', state: 'Indiana', county: 'Tippecanoe County' },
    { id: 'in-vnso', state: 'Indiana', county: 'Vanderburgh County' },
    { id: 'in-vrso', state: 'Indiana', county: 'Vermillion County' },
    { id: 'in-vcso', state: 'Indiana', county: 'Vigo County' },
    { id: 'in-wcso', state: 'Indiana', county: 'Whitley County' },
    { id: 'ia-amso', state: 'Iowa', county: 'Adams Co' },
    { id: 'ia-apcj', state: 'Iowa', county: 'Appanoose County' },
    { id: 'ia-acso', state: 'Iowa', county: 'Audubon Co' },
    { id: 'ia-bhcso', state: 'Iowa', county: 'Black Hawk Co' },
    { id: 'ia-bnso', state: 'Iowa', county: 'Boone Co' },
    { id: 'ia-brso', state: 'Iowa', county: 'Bremer County' },
    { id: 'ia-bcso', state: 'Iowa', county: 'Buchanan Co' },
    { id: 'ia-bvcso', state: 'Iowa', county: 'Buena Vista Co' },
    { id: 'ia-btso', state: 'Iowa', county: 'Butler Co' },
    { id: 'ia-ccso', state: 'Iowa', county: 'Carroll Co' },
    { id: 'ia-csso', state: 'Iowa', county: 'Cass County' },
    { id: 'ia-cdso', state: 'Iowa', county: 'Cedar Co' },
    { id: 'ia-cgcso', state: 'Iowa', county: 'Cerro Gordo Co' },
    { id: 'ia-chso', state: 'Iowa', county: 'Chickasaw Co' },
    { id: 'ia-ckso', state: 'Iowa', county: 'Clarke Co' },
    { id: 'ia-clyso', state: 'Iowa', county: 'Clay County' },
    { id: 'ia-cyso', state: 'Iowa', county: 'Clayton Co' },
    { id: 'ia-ccsd', state: 'Iowa', county: 'Crawford Co' },
    { id: 'ia-dcsd', state: 'Iowa', county: 'Dallas Co' },
    { id: 'ia-dcso', state: 'Iowa', county: 'Davis Co' },
    { id: 'ia-dcj', state: 'Iowa', county: 'Decatur County' },
    { id: 'ia-dlso', state: 'Iowa', county: 'Delaware Co' },
    { id: 'ia-dmcso', state: 'Iowa', county: 'Des Moines Co' },
    { id: 'ia-dubu', state: 'Iowa', county: 'Dubuque County' },
    { id: 'ia-ecso', state: 'Iowa', county: 'Emmett Co' },
    { id: 'ia-fcso', state: 'Iowa', county: 'Fayette County' },
    { id: 'ia-gcso', state: 'Iowa', county: 'Grundy Co' },
    { id: 'ia-hrso', state: 'Iowa', county: 'Hardin County' },
    { id: 'ia-hcso', state: 'Iowa', county: 'Harrison Co' },
    { id: 'ia-hcsd', state: 'Iowa', county: 'Henry Co' },
    { id: 'ia-hmso', state: 'Iowa', county: 'Humboldt Co' },
    { id: 'ia-idc', state: 'Iowa', county: 'Iowa Department of Corrections' },
    { id: 'ia-jcso', state: 'Iowa', county: 'Jackson Co' },
    { id: 'ia-jsso', state: 'Iowa', county: 'Jasper Co' },
    { id: 'ia-jfso', state: 'Iowa', county: 'Jefferson Co' },
    { id: 'ia-jhso', state: 'Iowa', county: 'Johnson Co' },
    { id: 'ia-kcso', state: 'Iowa', county: 'Keokuk Co' },
    { id: 'ia-leso', state: 'Iowa', county: 'Lee Co' },
    { id: 'ia-lnso', state: 'Iowa', county: 'Linn Co' },
    { id: 'ia-lcso', state: 'Iowa', county: 'Louisa Co' },
    { id: 'ia-lsso', state: 'Iowa', county: 'Lucas Co' },
    { id: 'ia-mdso', state: 'Iowa', county: 'Madison Co' },
    { id: 'ia-mrso', state: 'Iowa', county: 'Marion County' },
    { id: 'ia-mrshll', state: 'Iowa', county: 'Marshall County' },
    { id: 'ia-mlso', state: 'Iowa', county: 'Mills Co' },
    { id: 'ia-mtso', state: 'Iowa', county: 'Mitchell Co' },
    { id: 'ia-mnso', state: 'Iowa', county: 'Monona Co' },
    { id: 'ia-mcso', state: 'Iowa', county: 'Monroe Co' },
    { id: 'ia-mgso', state: 'Iowa', county: 'Montgomery Co' },
    { id: 'ia-msso', state: 'Iowa', county: 'Muscatine Co' },
    { id: 'ia-ocso', state: 'Iowa', county: "O'Brien Co" },
    { id: 'ia-pgso', state: 'Iowa', county: 'Page Co' },
    { id: 'ia-plso', state: 'Iowa', county: 'Plymouth Co' },
    { id: 'ia-phso', state: 'Iowa', county: 'Pocahontas Co' },
    { id: 'ia-pcso', state: 'Iowa', county: 'Polk County' },
    { id: 'ia-ptso', state: 'Iowa', county: 'Pottawattamie Co' },
    { id: 'ia-pwso', state: 'Iowa', county: 'Poweshiek Co' },
    { id: 'ia-sccj', state: 'Iowa', county: 'Scott County' },
    { id: 'ia-scso', state: 'Iowa', county: 'Shelby Co' },
    { id: 'ia-schd', state: 'Iowa', county: 'Sioux Co' },
    { id: 'ia-sdso', state: 'Iowa', county: 'Story County' },
    { id: 'ia-tcso', state: 'Iowa', county: 'Tama County' },
    { id: 'ia-taso', state: 'Iowa', county: 'Taylor Co' },
    { id: 'ia-ucso', state: 'Iowa', county: 'Union Co' },
    { id: 'ia-vcso', state: 'Iowa', county: 'Van Buren Co' },
    { id: 'ia-wacso', state: 'Iowa', county: 'Wapello Co' },
    { id: 'ia-wcso', state: 'Iowa', county: 'Warren County' },
    { id: 'ia-wshso', state: 'Iowa', county: 'Washington Co' },
    { id: 'ia-wcjd', state: 'Iowa', county: 'Webster County' },
    { id: 'ia-wfso', state: 'Iowa', county: 'Winnebago Co' },
    { id: 'ia-wshcj', state: 'Iowa', county: 'Winneshiek County' },
    { id: 'ia-wrso', state: 'Iowa', county: 'Woodbury Co' },
    { id: 'ia-wrscd', state: 'Iowa', county: 'Worth Co' },
    { id: 'ia-wyso', state: 'Iowa', county: 'Wright Co' },
    { id: 'ks-ccso', state: 'Kansas', county: 'Cherokee County' },
    { id: 'ks-pcso', state: 'Kansas', county: 'Pratt County' },
    { id: 'ks-scso', state: 'Kansas', county: 'Sedgwick County' },
    { id: 'ky-acso', state: 'Kentucky', county: 'Adair County' },
    { id: 'ky-acdc', state: 'Kentucky', county: 'Allen County' },
    { id: 'ky-bcdc', state: 'Kentucky', county: 'Ballard County' },
    { id: 'ky-bndc', state: 'Kentucky', county: 'Barren County' },
    { id: 'ky-bcj', state: 'Kentucky', county: 'Bell County' },
    { id: 'ky-bsdc', state: 'Kentucky', county: 'Big Sandy Regional' },
    { id: 'ky-budc', state: 'Kentucky', county: 'Bourbon County' },
    { id: 'ky-bydc', state: 'Kentucky', county: 'Boyd County' },
    { id: 'ky-bldc', state: 'Kentucky', county: 'Boyle County' },
    { id: 'ky-bcso', state: 'Kentucky', county: 'Breckenridge County' },
    { id: 'ky-bddc', state: 'Kentucky', county: 'Breckinridge County' },
    { id: 'ky-blso', state: 'Kentucky', county: 'Bullitt County' },
    { id: 'ky-ccj', state: 'Kentucky', county: 'Calloway County' },
    { id: 'ky-cpdc', state: 'Kentucky', county: 'Campbell County' },
    { id: 'ky-ccdc', state: 'Kentucky', county: 'Carroll County' },
    { id: 'ky-cadc', state: 'Kentucky', county: 'Carter County' },
    { id: 'ky-cyj', state: 'Kentucky', county: 'Casey County' },
    { id: 'ky-ccsd', state: 'Kentucky', county: 'Christian County' },
    { id: 'ky-ckdc', state: 'Kentucky', county: 'Clark County' },
    { id: 'ky-cldc', state: 'Kentucky', county: 'Clay County' },
    { id: 'ky-ctdc', state: 'Kentucky', county: 'Crittenden County' },
    { id: 'ky-dcdc', state: 'Kentucky', county: 'Daviess County' },
    { id: 'ky-fcrj', state: 'Kentucky', county: 'Franklin County Regional' },
    { id: 'ky-fcdc', state: 'Kentucky', county: 'Fulton County' },
    { id: 'ky-gcj', state: 'Kentucky', county: 'Grant County' },
    { id: 'ky-gcsd', state: 'Kentucky', county: 'Grayson County' },
    { id: 'ky-grsd', state: 'Kentucky', county: 'Greenup County' },
    { id: 'ky-hcdc', state: 'Kentucky', county: 'Hardin County' },
    { id: 'ky-hndc', state: 'Kentucky', county: 'Harlan County' },
    { id: 'ky-hcj', state: 'Kentucky', county: 'Hart County' },
    { id: 'ky-hedc', state: 'Kentucky', county: 'Henderson County' },
    { id: 'ky-hcso', state: 'Kentucky', county: 'Hickman County' },
    { id: 'ky-hocj', state: 'Kentucky', county: 'Hopkins County' },
    { id: 'ky-jcdc', state: 'Kentucky', county: 'Jackson County' },
    { id: 'ky-jcso', state: 'Kentucky', county: 'Jessamine County' },
    { id: 'ky-kcdc', state: 'Kentucky', county: 'Kenton County' },
    { id: 'ky-kcso', state: 'Kentucky', county: 'Knox County' },
    { id: 'ky-lcdc', state: 'Kentucky', county: 'Larue County' },
    { id: 'ky-lccc', state: 'Kentucky', county: 'Laurel County' },
    { id: 'ky-ledc', state: 'Kentucky', county: 'Leslie County' },
    { id: 'ky-lcso', state: 'Kentucky', county: 'Letcher County' },
    { id: 'ky-lsdc', state: 'Kentucky', county: 'Lewis County' },
    { id: 'ky-lnrj', state: 'Kentucky', county: 'Lincoln County Regional' },
    { id: 'ky-lcj', state: 'Kentucky', county: 'Logan County' },
    { id: 'ky-mcdc', state: 'Kentucky', county: 'Madison County' },
    { id: 'ky-mndc', state: 'Kentucky', county: 'Marion County' },
    { id: 'ky-mcso', state: 'Kentucky', county: 'Marshall County' },
    { id: 'ky-madc', state: 'Kentucky', county: 'Mason County' },
    { id: 'ky-mccj', state: 'Kentucky', county: 'McCracken County' },
    { id: 'ky-mrdc', state: 'Kentucky', county: 'McCreary County' },
    { id: 'ky-mcsd', state: 'Kentucky', county: 'Meade County' },
    { id: 'ky-mecc', state: 'Kentucky', county: 'Monroe County' },
    { id: 'ky-mgrj', state: 'Kentucky', county: 'Montgomery County Regional' },
    { id: 'ky-mhsd', state: 'Kentucky', county: 'Muhlenberg County' },
    { id: 'ky-ncso', state: 'Kentucky', county: 'Nelson County' },
    { id: 'ky-ocdc', state: 'Kentucky', county: 'Ohio County' },
    { id: 'ky-ocj', state: 'Kentucky', county: 'Oldham County' },
    { id: 'ky-prso', state: 'Kentucky', county: 'Perry County' },
    { id: 'ky-pcdc', state: 'Kentucky', county: 'Pike County' },
    { id: 'ky-pcso', state: 'Kentucky', county: 'Powell County' },
    { id: 'ky-pudc', state: 'Kentucky', county: 'Pulaski County' },
    { id: 'ky-rcdc', state: 'Kentucky', county: 'Rockcastle County' },
    { id: 'ky-rcsd', state: 'Kentucky', county: 'Rowan County' },
    { id: 'ky-rsdc', state: 'Kentucky', county: 'Russell County' },
    { id: 'ky-stsd', state: 'Kentucky', county: 'Scott County' },
    { id: 'ky-scsd', state: 'Kentucky', county: 'Shelby County' },
    { id: 'ky-scdc', state: 'Kentucky', county: 'Simpson County' },
    { id: 'ky-tcdc', state: 'Kentucky', county: 'Taylor County' },
    { id: 'ky-tfrj', state: 'Kentucky', county: 'Three Forks Regional' },
    { id: 'ky-ucj', state: 'Kentucky', county: 'Union County' },
    { id: 'ky-wcso', state: 'Kentucky', county: 'Warren County' },
    { id: 'ky-wayne', state: 'Kentucky', county: 'Wayne County' },
    { id: 'ky-wcj', state: 'Kentucky', county: 'Webster County' },
    { id: 'ky-wcdc', state: 'Kentucky', county: 'Whitley County' },
    { id: 'ky-wddc', state: 'Kentucky', county: 'Woodford County' },
    { id: 'la-acso', state: 'Louisiana', county: 'Allen Parish County' },
    { id: 'la-apso', state: 'Louisiana', county: 'Ascension Parish County' },
    { id: 'la-cadd', state: 'Louisiana', county: 'Caddo Parish' },
    { id: 'la-lpcso', state: 'Louisiana', county: 'Lafourche Parish County' },
    { id: 'la-opso', state: 'Louisiana', county: 'Ouachita Parish County' },
    { id: 'la-rpso', state: 'Louisiana', county: 'Rapides Parish County' },
    { id: 'la-sjpso', state: 'Louisiana', county: 'St. James Parish County' },
    { id: 'la-smpso', state: 'Louisiana', county: 'St. Mary Parish County' },
    { id: 'md-bcso', state: 'Maryland', county: 'Baltimore County' },
    { id: 'md-dcso', state: 'Maryland', county: 'Dorchester County' },
    { id: 'md-mont', state: 'Maryland', county: 'Montgomery County' },
    { id: 'md-pg', state: 'Maryland', county: "Prince George's County" },
    { id: 'mi-acsd', state: 'Michigan', county: 'Alpena Co' },
    { id: 'mi-bcsd', state: 'Michigan', county: 'Barry Co' },
    { id: 'mi-ccsd', state: 'Michigan', county: 'Clinton Co' },
    { id: 'mi-ecso', state: 'Michigan', county: 'Eaton County' },
    { id: 'mi-icsd', state: 'Michigan', county: 'Isabella Co' },
    { id: 'mi-jcso', state: 'Michigan', county: 'Jackson County' },
    { id: 'mi-kcsd', state: 'Michigan', county: 'Kent County' },
    { id: 'mi-lcso', state: 'Michigan', county: 'Lake County' },
    { id: 'mi-mcso', state: 'Michigan', county: 'Macomb County' },
    { id: 'mi-mtso', state: 'Michigan', county: 'Mecosta Co' },
    { id: 'mi-mnsd', state: 'Michigan', county: 'Menominee Co' },
    { id: 'mi-mcsd', state: 'Michigan', county: 'Midland Co' },
    { id: 'mi-monr', state: 'Michigan', county: 'Monroe County' },
    { id: 'mi-mnso', state: 'Michigan', county: 'Montcalm Co' },
    { id: 'mi-musk', state: 'Michigan', county: 'Muskegon County' },
    { id: 'mi-oakl', state: 'Michigan', county: 'Oakland' },
    { id: 'mi-wayn', state: 'Michigan', county: 'Wayne County' },
    { id: 'mn-acso', state: 'Minnesota', county: 'Anoka County' },
    { id: 'mn-hcso', state: 'Minnesota', county: 'Hennepin County' },
    { id: 'mn-mcso', state: 'Minnesota', county: 'Mower County' },
    { id: 'mn-scj', state: 'Minnesota', county: 'Scott County' },
    { id: 'mn-wrcj', state: 'Minnesota', county: 'Wright County' },
    { id: 'ms-acso', state: 'Mississippi', county: 'Adams County' },
    { id: 'ms-bcsd', state: 'Mississippi', county: 'Bolivar County' },
    { id: 'ms-cnsd', state: 'Mississippi', county: 'Calhoun County' },
    { id: 'ms-ccsd', state: 'Mississippi', county: 'Choctaw County' },
    { id: 'ms-clsd', state: 'Mississippi', county: 'Clarke County' },
    { id: 'ms-clay', state: 'Mississippi', county: 'Clay County' },
    { id: 'ms-ccso', state: 'Mississippi', county: 'Covington County' },
    { id: 'ms-deso', state: 'Mississippi', county: 'DeSoto County' },
    { id: 'ms-fcso', state: 'Mississippi', county: 'Forrest County' },
    { id: 'ms-gcso', state: 'Mississippi', county: 'George County' },
    { id: 'ms-hanc', state: 'Mississippi', county: 'Hancock County' },
    { id: 'ms-hcso', state: 'Mississippi', county: 'Harrison County' },
    { id: 'ms-hind', state: 'Mississippi', county: 'Hinds County' },
    { id: 'ms-hlsd', state: 'Mississippi', county: 'Holmes County' },
    { id: 'ms-hcsd', state: 'Mississippi', county: 'Humphreys County' },
    { id: 'ms-jcsd', state: 'Mississippi', county: 'Jackson County' },
    { id: 'ms-jssd', state: 'Mississippi', county: 'Jasper County' },
    { id: 'ms-jfsd', state: 'Mississippi', county: 'Jefferson County' },
    { id: 'ms-jcso', state: 'Mississippi', county: 'Jones County' },
    { id: 'ms-kcsd', state: 'Mississippi', county: 'Kemper County' },
    { id: 'ms-lama', state: 'Mississippi', county: 'Lamar County' },
    { id: 'ms-lcsd', state: 'Mississippi', county: 'Lauderdale County' },
    { id: 'ms-lwso', state: 'Mississippi', county: 'Lawrence County' },
    { id: 'ms-lcso', state: 'Mississippi', county: 'Leake County' },
    { id: 'ms-lee', state: 'Mississippi', county: 'Lee County' },
    { id: 'ms-ldso', state: 'Mississippi', county: 'Lowndes County' },
    { id: 'ms-mcso', state: 'Mississippi', county: 'Monroe County' },
    { id: 'ms-pcso', state: 'Mississippi', county: 'Perry County' },
    { id: 'ms-pcsd', state: 'Mississippi', county: 'Pontotoc County' },
    { id: 'ms-prsd', state: 'Mississippi', county: 'Prentiss County' },
    { id: 'ms-rcsd', state: 'Mississippi', county: 'Rankin County' },
    { id: 'ms-scso', state: 'Mississippi', county: 'Scott County' },
    { id: 'ms-scsd', state: 'Mississippi', county: 'Smith County' },
    { id: 'ms-stsd', state: 'Mississippi', county: 'Stone County' },
    { id: 'ms-snso', state: 'Mississippi', county: 'Sunflower County' },
    { id: 'ms-tgsd', state: 'Mississippi', county: 'Tishomingo County' },
    { id: 'ms-tcso', state: 'Mississippi', county: 'Tunica County' },
    { id: 'ms-ucso', state: 'Mississippi', county: 'Union County' },
    { id: 'ms-wssd', state: 'Mississippi', county: 'Washington County' },
    { id: 'ms-wcsd', state: 'Mississippi', county: 'Wayne County' },
    { id: 'ms-wbso', state: 'Mississippi', county: 'Webster County' },
    { id: 'ms-wcso', state: 'Mississippi', county: 'Wilkinson County' },
    { id: 'ms-yasd', state: 'Mississippi', county: 'Yalobusha County' },
    { id: 'ms-ycso', state: 'Mississippi', county: 'Yazoo County' },
    { id: 'mo-acso', state: 'Missouri', county: 'Adair County' },
    { id: 'mo-asso', state: 'Missouri', county: 'Atchison County' },
    { id: 'mo-bcso', state: 'Missouri', county: 'Barry County' },
    { id: 'mo-brso', state: 'Missouri', county: 'Barton County' },
    { id: 'mo-btso', state: 'Missouri', county: 'Bates County' },
    { id: 'mo-bncj', state: 'Missouri', county: 'Benton County' },
    { id: 'mo-boll', state: 'Missouri', county: 'Bollinger County' },
    { id: 'mo-bcsd', state: 'Missouri', county: 'Boone County' },
    { id: 'mo-bpd', state: 'Missouri', county: 'Branson Police Dept' },
    { id: 'mo-bhso', state: 'Missouri', county: 'Buchanan County' },
    { id: 'mo-bcs', state: 'Missouri', county: 'Butler County' },
    { id: 'mo-ccso', state: 'Missouri', county: 'Caldwell County' },
    { id: 'mo-clso', state: 'Missouri', county: 'Callaway County' },
    { id: 'mo-camd', state: 'Missouri', county: 'Camden County' },
    { id: 'mo-cgcj', state: 'Missouri', county: 'Cape Girardeau County' },
    { id: 'mo-cdso', state: 'Missouri', county: 'Cedar County' },
    { id: 'mo-ckso', state: 'Missouri', county: 'Clark County' },
    { id: 'mo-cyso', state: 'Missouri', county: 'Clay County' },
    { id: 'mo-coso', state: 'Missouri', county: 'Cole County' },
    { id: 'mo-cocj', state: 'Missouri', county: 'Cooper County' },
    { id: 'mo-cwcj', state: 'Missouri', county: 'Crawford County' },
    { id: 'mo-dcso', state: 'Missouri', county: 'Dunklin County' },
    { id: 'mo-fpd', state: 'Missouri', county: 'Florissant' },
    { id: 'mo-fcdc', state: 'Missouri', county: 'Franklin County Adult' },
    { id: 'mo-gree', state: 'Missouri', county: 'Greene County' },
    { id: 'mo-gcso', state: 'Missouri', county: 'Grundy County' },
    { id: 'mo-hpd', state: 'Missouri', county: 'Hazelwood' },
    { id: 'mo-hycj', state: 'Missouri', county: 'Henry County' },
    { id: 'mo-hlso', state: 'Missouri', county: 'Holt County' },
    { id: 'mo-hoco', state: 'Missouri', county: 'Howard County' },
    { id: 'mo-hcso', state: 'Missouri', county: 'Howell County' },
    { id: 'mo-jkdc', state: 'Missouri', county: 'Jackson County' },
    { id: 'mo-jpso', state: 'Missouri', county: 'Jasper County' },
    { id: 'mo-jecj', state: 'Missouri', county: 'Jefferson County' },
    { id: 'mo-jcso', state: 'Missouri', county: 'Johnson County' },
    { id: 'mo-lacj', state: 'Missouri', county: 'Laclede County' },
    { id: 'mo-lcsd', state: 'Missouri', county: 'Lafayette County' },
    { id: 'mo-lcso', state: 'Missouri', county: 'Lawrence County' },
    { id: 'mo-lnso', state: 'Missouri', county: 'Livingston County' },
    { id: 'mo-maco', state: 'Missouri', county: 'Macon County' },
    { id: 'mo-mhpd', state: 'Missouri', county: 'Maryland Heights' },
    { id: 'mo-mcdc', state: 'Missouri', county: 'McDonald County' },
    { id: 'mo-mcso', state: 'Missouri', county: 'Miller County' },
    { id: 'mo-mcs', state: 'Missouri', county: 'Mississippi County' },
    { id: 'mo-mdc', state: 'Missouri', county: 'Missouri Dept of Correction' },
    { id: 'mo-mcj', state: 'Missouri', county: 'Moniteau County' },
    { id: 'mo-monr', state: 'Missouri', county: 'Monroe County' },
    { id: 'mo-mns', state: 'Missouri', county: 'Montgomery County' },
    { id: 'mo-mrso', state: 'Missouri', county: 'Morgan County' },
    { id: 'mo-nmcso', state: 'Missouri', county: 'New Madrid County' },
    { id: 'mo-ncso', state: 'Missouri', county: 'Nodaway County' },
    { id: 'mo-ocso', state: 'Missouri', county: 'Osage County' },
    { id: 'mo-pmso', state: 'Missouri', county: 'Pemiscot County' },
    { id: 'mo-pycj', state: 'Missouri', county: 'Perry County' },
    { id: 'mo-ptso', state: 'Missouri', county: 'Pettis County' },
    { id: 'mo-pkso', state: 'Missouri', county: 'Pike County' },
    { id: 'mo-pcso', state: 'Missouri', county: 'Platte County' },
    { id: 'mo-pkcj', state: 'Missouri', county: 'Polk County' },
    { id: 'mo-pscj', state: 'Missouri', county: 'Pulaski County' },
    { id: 'mo-rcsd', state: 'Missouri', county: 'Randolph County' },
    { id: 'mo-rcso', state: 'Missouri', county: 'Reynolds County' },
    { id: 'mo-slso', state: 'Missouri', county: 'Saline County' },
    { id: 'mo-sccj', state: 'Missouri', county: 'Scott County' },
    { id: 'mo-scpd', state: 'Missouri', county: 'St. Charles' },
    { id: 'mo-sfcso', state: 'Missouri', county: 'St. Francois County' },
    { id: 'mo-slcpd', state: 'Missouri', county: 'St. Louis County' },
    { id: 'mo-slcso', state: 'Missouri', county: 'St. Louis County' },
    { id: 'mo-scsd', state: 'Missouri', county: 'Stoddard County' },
    { id: 'mo-scso', state: 'Missouri', county: 'Stone County' },
    { id: 'mo-tacj', state: 'Missouri', county: 'Taney County' },
    { id: 'mo-ucpd', state: 'Missouri', county: 'University City' },
    { id: 'mo-vcso', state: 'Missouri', county: 'Vernon County' },
    { id: 'mo-wrcj', state: 'Missouri', county: 'Warren County' },
    { id: 'mt-rcso', state: 'Montana', county: 'Ravalli County' },
    { id: 'ne-dcdc', state: 'Nebraska', county: 'Douglas County' },
    { id: 'nv-clv', state: 'Nevada', county: 'City of Las Vegas' },
    { id: 'nv-ccdc', state: 'Nevada', county: 'Clark County' },
    { id: 'nv-chn', state: 'Nevada', county: 'Henderson' },
    { id: 'nv-lcso', state: 'Nevada', county: 'Lincoln County' },
    { id: 'nv-lcsd', state: 'Nevada', county: 'Lyon County' },
    { id: 'nv-pcso', state: 'Nevada', county: 'Pershing County' },
    { id: 'nv-scso', state: 'Nevada', county: 'Storey County' },
    { id: 'nv-wcso', state: 'Nevada', county: 'Washoe County' },
    { id: 'nv-wpcso', state: 'Nevada', county: 'White Pine County' },
    { id: 'nj-bcso', state: 'New Jersey', county: 'Bergen County' },
    { id: 'nj-ecdc', state: 'New Jersey', county: 'Essex County' },
    { id: 'nj-hcso', state: 'New Jersey', county: 'Hudson County' },
    { id: 'nj-mcso', state: 'New Jersey', county: 'Mercer County' },
    { id: 'nj-monm', state: 'New Jersey', county: 'Monmouth County' },
    { id: 'nj-ocea', state: 'New Jersey', county: 'Ocean County' },
    { id: 'nj-pass', state: 'New Jersey', county: 'Passaic County' },
    { id: 'nm-bcsd', state: 'New Mexico', county: 'Bernalillo County Sheriff’s Department' },
    { id: 'nm-ccsd', state: 'New Mexico', county: 'Catron County' },
    { id: 'nm-chsd', state: 'New Mexico', county: 'Chaves County' },
    { id: 'nm-cbsd', state: 'New Mexico', county: 'Cibola County' },
    { id: 'nm-ccdc', state: 'New Mexico', county: 'Curry Co' },
    { id: 'nm-dacso', state: 'New Mexico', county: 'Dona Ana County' },
    { id: 'nm-gcdc', state: 'New Mexico', county: 'Grant County' },
    { id: 'nm-hcso', state: 'New Mexico', county: 'Hidalgo County' },
    { id: 'nm-lacdc', state: 'New Mexico', county: 'Los Alamos Co' },
    { id: 'nm-qcdc', state: 'New Mexico', county: 'Quay County' },
    { id: 'nm-racdc', state: 'New Mexico', county: 'Rio Arriba Co' },
    { id: 'nm-rcdc', state: 'New Mexico', county: 'Roosevelt Co' },
    { id: 'nm-smcdc', state: 'New Mexico', county: 'San Miguel Co' },
    { id: 'nm-scdc', state: 'New Mexico', county: 'Sandoval Co Dentention Center' },
    { id: 'nm-sfccd', state: 'New Mexico', county: 'Santa Fe County Corrections Department' },
    { id: 'nm-tcdc', state: 'New Mexico', county: 'Torrance Co' },
    { id: 'nm-ucdf', state: 'New Mexico', county: 'Union Countylty' },
    { id: 'nm-vmdc', state: 'New Mexico', county: 'Vigil Maldonado' },
    { id: 'ny-acso', state: 'New York', county: 'Allegany County' },
    { id: 'ny-bcj', state: 'New York', county: 'Broome County' },
    { id: 'ny-ctso', state: 'New York', county: 'Cattaraugus County' },
    { id: 'ny-cyso', state: 'New York', county: 'Cayuga County' },
    { id: 'ny-chso', state: 'New York', county: 'Chemung County' },
    { id: 'ny-c', state: 'New York', county: 'Chenango' },
    { id: 'ny-clcj', state: 'New York', county: 'Clinton County' },
    { id: 'ny-ccso', state: 'New York', county: 'Columbia County' },
    { id: 'ny-crso', state: 'New York', county: 'Cortland County' },
    { id: 'ny-dwcj', state: 'New York', county: 'Delaware County' },
    { id: 'ny-excj', state: 'New York', county: 'Essex County' },
    { id: 'ny-frcj', state: 'New York', county: 'Franklin County' },
    { id: 'ny-gnso', state: 'New York', county: 'Genesee County' },
    { id: 'ny-gcso', state: 'New York', county: 'Greene County' },
    { id: 'ny-hcso', state: 'New York', county: 'Herkimer County' },
    { id: 'ny-jcso', state: 'New York', county: 'Jefferson County' },
    { id: 'ny-lwso', state: 'New York', county: 'Lewis County' },
    { id: 'ny-lcso', state: 'New York', county: 'Livingston County' },
    { id: 'ny-mcso', state: 'New York', county: 'Madison County' },
    { id: 'ny-nyc', state: 'New York', county: 'New York City Department of Corrections' },
    { id: 'ny-nicj', state: 'New York', county: 'Niagara County' },
    { id: 'ny-olso', state: 'New York', county: 'Orleans County' },
    { id: 'ny-ocso', state: 'New York', county: 'Oswego County' },
    { id: 'ny-otcj', state: 'New York', county: 'Otsego County' },
    { id: 'ny-pcso', state: 'New York', county: 'Putnam County' },
    { id: 'ny-rcso', state: 'New York', county: 'Rockland County' },
    { id: 'ny-slco', state: 'New York', county: 'Schuyler County' },
    { id: 'ny-sncj', state: 'New York', county: 'Seneca County' },
    { id: 'ny-slcso', state: 'New York', county: 'St. Lawrence County' },
    { id: 'ny-stso', state: 'New York', county: 'Steuben County' },
    { id: 'ny-scso', state: 'New York', county: 'Sullivan County' },
    { id: 'ny-tcso', state: 'New York', county: 'Tioga County' },
    { id: 'ny-tmso', state: 'New York', county: 'Tompkins County' },
    { id: 'ny-wrso', state: 'New York', county: 'Warren County' },
    { id: 'ny-wcso', state: 'New York', county: 'Washington County' },
    { id: 'ny-wacj', state: 'New York', county: 'Wayne County' },
    { id: 'ny-ycso', state: 'New York', county: 'Yates County' },
    { id: 'nc-amso', state: 'North Carolina', county: 'Alamance County' },
    { id: 'nc-also', state: 'North Carolina', county: 'Alleghany County' },
    { id: 'nc-asso', state: 'North Carolina', county: 'Anson County' },
    { id: 'nc-acso', state: 'North Carolina', county: 'Ashe County' },
    { id: 'nc-arso', state: 'North Carolina', county: 'Avery County' },
    { id: 'nc-bcso', state: 'North Carolina', county: 'Bertie County' },
    { id: 'nc-blso', state: 'North Carolina', county: 'Bladen County' },
    { id: 'nc-brsd', state: 'North Carolina', county: 'Brunswick County' },
    { id: 'nc-bnso', state: 'North Carolina', county: 'Buncombe County' },
    { id: 'nc-brso', state: 'North Carolina', county: 'Burke County' },
    { id: 'nc-cbso', state: 'North Carolina', county: 'Cabarrus County' },
    { id: 'nc-cwso', state: 'North Carolina', county: 'Caldwell County' },
    { id: 'nc-ctso', state: 'North Carolina', county: 'Carteret County' },
    { id: 'nc-csso', state: 'North Carolina', county: 'Caswell County' },
    { id: 'nc-chso', state: 'North Carolina', county: 'Cherokee County' },
    { id: 'nc-cyso', state: 'North Carolina', county: 'Clay County' },
    { id: 'nc-ccso', state: 'North Carolina', county: 'Cleveland County' },
    { id: 'nc-clso', state: 'North Carolina', county: 'Columbus County' },
    { id: 'nc-cmso', state: 'North Carolina', county: 'Cumberland County' },
    { id: 'nc-crso', state: 'North Carolina', county: 'Currituck County' },
    { id: 'nc-daso', state: 'North Carolina', county: 'Dare County' },
    { id: 'nc-dvso', state: 'North Carolina', county: 'Davidson County' },
    { id: 'nc-dcso', state: 'North Carolina', county: 'Davie County' },
    { id: 'nc-dpso', state: 'North Carolina', county: 'Duplin County' },
    { id: 'nc-drso', state: 'North Carolina', county: 'Durham County' },
    { id: 'nc-ecso', state: 'North Carolina', county: 'Edgecombe County' },
    { id: 'nc-fors', state: 'North Carolina', county: 'Forsyth County' },
    { id: 'nc-fcso', state: 'North Carolina', county: 'Franklin County' },
    { id: 'nc-ghso', state: 'North Carolina', county: 'Graham County' },
    { id: 'nc-gnso', state: 'North Carolina', county: 'Granville County' },
    { id: 'nc-grso', state: 'North Carolina', county: 'Greene County' },
    { id: 'nc-gcso', state: 'North Carolina', county: 'Guilford County' },
    { id: 'nc-hcso', state: 'North Carolina', county: 'Halifax County' },
    { id: 'nc-hyso', state: 'North Carolina', county: 'Haywood County' },
    { id: 'nc-hnso', state: 'North Carolina', county: 'Henderson County' },
    { id: 'nc-hrso', state: 'North Carolina', county: 'Hertford County' },
    { id: 'nc-hkso', state: 'North Carolina', county: 'Hoke County' },
    { id: 'nc-icso', state: 'North Carolina', county: 'Iredell County' },
    { id: 'nc-jkso', state: 'North Carolina', county: 'Jackson County' },
    { id: 'nc-jcso', state: 'North Carolina', county: 'Jones County' },
    { id: 'nc-lcso', state: 'North Carolina', county: 'Lee County' },
    { id: 'nc-lnso', state: 'North Carolina', county: 'Lenoir County' },
    { id: 'nc-linc', state: 'North Carolina', county: 'Lincoln County' },
    { id: 'nc-mcnso', state: 'North Carolina', county: 'Macon County' },
    { id: 'nc-mdso', state: 'North Carolina', county: 'Madison County' },
    { id: 'nc-dwso', state: 'North Carolina', county: 'McDowell County' },
    { id: 'nc-mcso', state: 'North Carolina', county: 'Mecklenburg County' },
    { id: 'nc-mnso', state: 'North Carolina', county: 'Montgomery County' },
    { id: 'nc-mrso', state: 'North Carolina', county: 'Moore County' },
    { id: 'nc-morg', state: 'North Carolina', county: 'Morganton County' },
    { id: 'nc-nasd', state: 'North Carolina', county: 'Nash County' },
    { id: 'nc-nhcso', state: 'North Carolina', county: 'New Hanover County' },
    { id: 'nc-ncso', state: 'North Carolina', county: 'Northampton County' },
    { id: 'nc-ocso', state: 'North Carolina', county: 'Onslow County' },
    { id: 'nc-onso', state: 'North Carolina', county: 'Orange County' },
    { id: 'nc-pmso', state: 'North Carolina', county: 'Pamlico County' },
    { id: 'nc-pnso', state: 'North Carolina', county: 'Pender County' },
    { id: 'nc-prso', state: 'North Carolina', county: 'Person County' },
    { id: 'nc-ptso', state: 'North Carolina', county: 'Pitt County' },
    { id: 'nc-pcso', state: 'North Carolina', county: 'Polk County' },
    { id: 'nc-rand', state: 'North Carolina', county: 'Randolph County' },
    { id: 'nc-rcso', state: 'North Carolina', county: 'Robeson County' },
    { id: 'nc-rkso', state: 'North Carolina', county: 'Rockingham County' },
    { id: 'nc-rwso', state: 'North Carolina', county: 'Rowan County' },
    { id: 'nc-rtso', state: 'North Carolina', county: 'Rutherford County' },
    { id: 'nc-smso', state: 'North Carolina', county: 'Sampson County' },
    { id: 'nc-slso', state: 'North Carolina', county: 'Scotland County' },
    { id: 'nc-scso', state: 'North Carolina', county: 'Stanly County' },
    { id: 'nc-stso', state: 'North Carolina', county: 'Stokes County' },
    { id: 'nc-swso', state: 'North Carolina', county: 'Swain County' },
    { id: 'nc-tcso', state: 'North Carolina', county: 'Transylvania County' },
    { id: 'nc-vcso', state: 'North Carolina', county: 'Vance County' },
    { id: 'nc-wcso', state: 'North Carolina', county: 'Wake County' },
    { id: 'nc-wrso', state: 'North Carolina', county: 'Warren County' },
    { id: 'nc-wsso', state: 'North Carolina', county: 'Washington County' },
    { id: 'nc-wtso', state: 'North Carolina', county: 'Watauga County' },
    { id: 'nc-wyso', state: 'North Carolina', county: 'Wayne County' },
    { id: 'nc-wlso', state: 'North Carolina', county: 'Wilkes County' },
    { id: 'nc-wnso', state: 'North Carolina', county: 'Wilson County' },
    { id: 'nc-ydso', state: 'North Carolina', county: 'Yadkin County' },
    { id: 'nc-ycso', state: 'North Carolina', county: 'Yancey County' },
    { id: 'nd-bcso', state: 'North Dakota', county: 'Burleigh County' },
    { id: 'nd-ccso', state: 'North Dakota', county: 'Cass County' },
    { id: 'nd-wcso', state: 'North Dakota', county: 'Williams County' },
    { id: 'oh-acso', state: 'Ohio', county: 'Adams County' },
    { id: 'oh-bcso', state: 'Ohio', county: 'Brown County' },
    { id: 'oh-btso', state: 'Ohio', county: 'Butler County' },
    { id: 'oh-ccso', state: 'Ohio', county: 'Clark County' },
    { id: 'oh-clso', state: 'Ohio', county: 'Clermont County' },
    { id: 'oh-cltn', state: 'Ohio', county: 'Clinton County' },
    { id: 'oh-csso', state: 'Ohio', county: 'Coshocton County' },
    { id: 'oh-cuya', state: 'Ohio', county: 'Cuyahoga County' },
    { id: 'oh-dcso', state: 'Ohio', county: 'Darke County' },
    { id: 'oh-frso', state: 'Ohio', county: 'Fairfield County' },
    { id: 'oh-fcso', state: 'Ohio', county: 'Fayette County' },
    { id: 'oh-fran', state: 'Ohio', county: 'Franklin County' },
    { id: 'oh-gcso', state: 'Ohio', county: 'Green County' },
    { id: 'oh-hcso', state: 'Ohio', county: 'Hamilton County' },
    { id: 'oh-hiso', state: 'Ohio', county: 'Highland County' },
    { id: 'oh-lick', state: 'Ohio', county: 'Licking County' },
    { id: 'oh-lcso', state: 'Ohio', county: 'Logan County' },
    { id: 'oh-lc', state: 'Ohio', county: 'Lorain County' },
    { id: 'oh-luca', state: 'Ohio', county: 'Lucas County' },
    { id: 'oh-mckj', state: 'Ohio', county: 'Montgomery County Kettering' },
    { id: 'oh-mcso', state: 'Ohio', county: 'Montgomery County' },
    { id: 'oh-pcso', state: 'Ohio', county: 'Preble County' },
    { id: 'oh-shso', state: 'Ohio', county: 'Shelby County' },
    { id: 'oh-scso', state: 'Ohio', county: 'Summit County' },
    { id: 'oh-suwa', state: 'Ohio', county: 'Suwannee County' },
    { id: 'oh-tcrj', state: 'Ohio', county: 'Tri-County Regional' },
    { id: 'oh-wcso', state: 'Ohio', county: 'Warren County' },
    { id: 'oh-wyso', state: 'Ohio', county: 'Wayne County' },
    { id: 'oh-wood', state: 'Ohio', county: 'Wood County' },
    { id: 'ok-ccso', state: 'Oklahoma', county: 'Cleveland County' },
    { id: 'ok-lcso', state: 'Oklahoma', county: 'Lincoln County' },
    { id: 'ok-ocso', state: 'Oklahoma', county: 'Oklahoma County' },
    { id: 'ok-rcso', state: 'Oklahoma', county: 'Rogers County' },
    { id: 'ok-tcso', state: 'Oklahoma', county: 'Tulsa County' },
    { id: 'ok-wcso', state: 'Oklahoma', county: 'Woods County' },
    { id: 'or-clac', state: 'Oregon', county: 'Clackamas County' },
    { id: 'or-ccso', state: 'Oregon', county: 'Columbia County' },
    { id: 'or-dcso', state: 'Oregon', county: 'Deschutes County' },
    { id: 'or-jcso', state: 'Oregon', county: 'Jackson County' },
    { id: 'or-lcso', state: 'Oregon', county: 'Lincoln County' },
    { id: 'or-linn', state: 'Oregon', county: 'Linn County' },
    { id: 'or-mcso', state: 'Oregon', county: 'Marion County' },
    { id: 'or-mucso', state: 'Oregon', county: 'Multnomah County' },
    { id: 'or-wcsc', state: 'Oregon', county: 'Washington County' },
    { id: 'or-ycso', state: 'Oregon', county: 'Yamhill County' },
    { id: 'pa-bcso', state: 'Pennsylvania', county: 'Butler County' },
    { id: 'pa-cent', state: 'Pennsylvania', county: 'Centre County' },
    { id: 'pa-phil', state: 'Pennsylvania', county: 'George W. Hill' },
    { id: 'pa-wmlc', state: 'Pennsylvania', county: 'Westmoreland County Prison' },
    { id: 'sc-abso', state: 'South Carolina', county: 'Abbeville County' },
    { id: 'sc-acso', state: 'South Carolina', county: 'Aiken County' },
    { id: 'sc-adso', state: 'South Carolina', county: 'Anderson County' },
    { id: 'sc-bcso', state: 'South Carolina', county: 'Bamberg County' },
    { id: 'sc-beauf', state: 'South Carolina', county: 'Beaufort County' },
    { id: 'sc-brso', state: 'South Carolina', county: 'Berkeley County' },
    { id: 'sc-chso', state: 'South Carolina', county: 'Charleston County' },
    { id: 'sc-chrk', state: 'South Carolina', county: 'Cherokee County' },
    { id: 'sc-ccso', state: 'South Carolina', county: 'Chester County' },
    { id: 'sc-ccpc', state: 'South Carolina', county: 'Chesterfield County' },
    { id: 'sc-clso', state: 'South Carolina', county: 'Colleton County' },
    { id: 'sc-dcdc', state: 'South Carolina', county: 'Dillon County' },
    { id: 'sc-ecdc', state: 'South Carolina', county: 'Edgefield County' },
    { id: 'sc-fcso', state: 'South Carolina', county: 'Fairfield County' },
    { id: 'sc-grso', state: 'South Carolina', county: 'Georgetown County' },
    { id: 'sc-gcso', state: 'South Carolina', county: 'Greenwood County' },
    { id: 'sc-hcsd', state: 'South Carolina', county: 'Hampton County' },
    { id: 'sc-hcso', state: 'South Carolina', county: 'Horry County' },
    { id: 'sc-jcso', state: 'South Carolina', county: 'Jasper County' },
    { id: 'sc-kcso', state: 'South Carolina', county: 'Kershaw County' },
    { id: 'sc-lcejdc', state: 'South Carolina', county: 'Laurens County' },
    { id: 'sc-lcdc', state: 'South Carolina', county: 'Lexington County' },
    { id: 'sc-mcj', state: 'South Carolina', county: 'Marion County' },
    { id: 'sc-mcdc', state: 'South Carolina', county: 'Marlboro County' },
    { id: 'sc-ncso', state: 'South Carolina', county: 'Newberry County Sheriff Office' },
    { id: 'sc-nmbpd', state: 'South Carolina', county: 'North Myrtle Beach' },
    { id: 'sc-ocon', state: 'South Carolina', county: 'Oconee County' },
    { id: 'sc-ocso', state: 'South Carolina', county: 'Orangeburg County' },
    { id: 'sc-pcpc', state: 'South Carolina', county: 'Pickens County Prison Camp' },
    { id: 'sc-scso', state: 'South Carolina', county: 'Saluda County' },
    { id: 'sc-spar', state: 'South Carolina', county: 'Spartanburg County' },
    { id: 'sc-sumt', state: 'South Carolina', county: 'Sumter County' },
    { id: 'sc-ucso', state: 'South Carolina', county: 'Union County' },
    { id: 'sc-wcj', state: 'South Carolina', county: 'Williamsburg County' },
    { id: 'sc-ycdcjc', state: 'South Carolina', county: 'York County' },
    { id: 'sd-ccso', state: 'South Dakota', county: 'Clay County' },
    { id: 'sd-mcso', state: 'South Dakota', county: 'Minnehaha County' },
    { id: 'tn-ccso', state: 'Tennessee', county: 'Cannon County' },
    { id: 'tn-cart', state: 'Tennessee', county: 'Carter County' },
    { id: 'tn-c', state: 'Tennessee', county: 'Clay' },
    { id: 'tn-cksd', state: 'Tennessee', county: 'Crockett County' },
    { id: 'tn-dysd', state: 'Tennessee', county: 'Dyer County' },
    { id: 'tn-fysd', state: 'Tennessee', county: 'Fayette County' },
    { id: 'tn-f', state: 'Tennessee', county: 'Franklin' },
    { id: 'tn-gcso', state: 'Tennessee', county: 'Giles County' },
    { id: 'tn-gcsd', state: 'Tennessee', county: 'Greene County' },
    { id: 'tn-grsd', state: 'Tennessee', county: 'Grundy County' },
    { id: 'tn-hcso', state: 'Tennessee', county: 'Hamilton County' },
    { id: 'tn-jcso', state: 'Tennessee', county: 'Johnson County' },
    { id: 'tn-kcso', state: 'Tennessee', county: 'Knox County' },
    { id: 'tn-lcso', state: 'Tennessee', county: 'Loudoun County' },
    { id: 'tn-mcso', state: 'Tennessee', county: 'Marshall County' },
    { id: 'tn-mrsd', state: 'Tennessee', county: 'Moore County' },
    { id: 'tn-mcsd', state: 'Tennessee', county: 'Morgan County' },
    { id: 'tn-rhea', state: 'Tennessee', county: 'Rhea County' },
    { id: 'tn-rcso', state: 'Tennessee', county: 'Roane County' },
    { id: 'tn-rbso', state: 'Tennessee', county: 'Robertson County' },
    { id: 'tn-rusd', state: 'Tennessee', county: 'Rutherford County' },
    { id: 'tn-scso', state: 'Tennessee', county: 'Shelby County' },
    { id: 'tn-scsd', state: 'Tennessee', county: 'Smith County' },
    { id: 'tn-tipt', state: 'Tennessee', county: 'Tipton County' },
    { id: 'tn-wlso', state: 'Tennessee', county: 'Williamson County' },
    { id: 'tn-wcso', state: 'Tennessee', county: 'Wilson County' },
    { id: 'tx-acso', state: 'Texas', county: 'Angelina County' },
    { id: 'tx-bcsd', state: 'Texas', county: 'Bell County' },
    { id: 'tx-brso', state: 'Texas', county: 'Brazos County' },
    { id: 'tx-bcso', state: 'Texas', county: 'Brown County' },
    { id: 'tx-clhn', state: 'Texas', county: 'Calhoun County' },
    { id: 'tx-cc', state: 'Texas', county: 'Cameron County' },
    { id: 'tx-chso', state: 'Texas', county: 'Chambers County' },
    { id: 'tx-ckcj', state: 'Texas', county: 'Cherokee County' },
    { id: 'tx-ccso', state: 'Texas', county: 'Collin County' },
    { id: 'tx-comal', state: 'Texas', county: 'Comal County' },
    { id: 'tx-dlso', state: 'Texas', county: 'Dallam County' },
    { id: 'tx-dc', state: 'Texas', county: 'Dallas County' },
    { id: 'tx-dcso', state: 'Texas', county: 'Denton County' },
    { id: 'tx-ector', state: 'Texas', county: 'Ector County' },
    { id: 'tx-ellis', state: 'Texas', county: 'Ellis County' },
    { id: 'tx-ecso', state: 'Texas', county: 'Erath County' },
    { id: 'tx-fbco', state: 'Texas', county: 'Fort Bend County' },
    { id: 'tx-gppd', state: 'Texas', county: 'Galena Park' },
    { id: 'tx-galv', state: 'Texas', county: 'Galveston County' },
    { id: 'tx-gcso', state: 'Texas', county: 'Garza County' },
    { id: 'tx-gcs', state: 'Texas', county: 'Gregg County Sheriff' },
    { id: 'tx-gdlp', state: 'Texas', county: 'Guadalupe County' },
    { id: 'tx-hcso', state: 'Texas', county: 'Harris County' },
    { id: 'tx-hays', state: 'Texas', county: 'Hays County' },
    { id: 'tx-hlso', state: 'Texas', county: 'Hill County' },
    { id: 'tx-hdso', state: 'Texas', county: 'Hood County' },
    { id: 'tx-hwrd', state: 'Texas', county: 'Howard County' },
    { id: 'tx-htcj', state: 'Texas', county: 'Hunt County' },
    { id: 'tx-hpd', state: 'Texas', county: 'Hurst' },
    { id: 'tx-jkcj', state: 'Texas', county: 'Jackson County' },
    { id: 'tx-jcso', state: 'Texas', county: 'Johnson County' },
    { id: 'tx-kcso', state: 'Texas', county: 'Kaufman County' },
    { id: 'tx-kerr', state: 'Texas', county: 'Kerr County' },
    { id: 'tx-klso', state: 'Texas', county: 'Kleberg County' },
    { id: 'tx-lcso', state: 'Texas', county: 'Lamar County' },
    { id: 'tx-mans', state: 'Texas', county: 'Mansfield County' },
    { id: 'tx-mdcj', state: 'Texas', county: 'Midland County' },
    { id: 'tx-mcso', state: 'Texas', county: 'Montgomery County' },
    { id: 'tx-mrcj', state: 'Texas', county: 'Moore County' },
    { id: 'tx-ncso', state: 'Texas', county: 'Nacogdoches County' },
    { id: 'tx-pear', state: 'Texas', county: 'Pearland County' },
    { id: 'tx-pcso', state: 'Texas', county: 'Polk County' },
    { id: 'tx-ptcj', state: 'Texas', county: 'Potter County' },
    { id: 'tx-rcso', state: 'Texas', county: 'Rockwall County' },
    { id: 'tx-scso', state: 'Texas', county: 'Smith County' },
    { id: 'tx-tc', state: 'Texas', county: 'Tarrant County' },
    { id: 'tx-tlr', state: 'Texas', county: 'Taylor County' },
    { id: 'tx-tts', state: 'Texas', county: 'Titus County' },
    { id: 'tx-green', state: 'Texas', county: 'Tom Green County' },
    { id: 'tx-trso', state: 'Texas', county: 'Travis County' },
    { id: 'tx-tcso', state: 'Texas', county: 'Trinity County' },
    { id: 'tx-vzcso', state: 'Texas', county: 'Van Zandt County' },
    { id: 'tx-wcso', state: 'Texas', county: 'Waller County' },
    { id: 'tx-chcj', state: 'Texas', county: 'Wharton County' },
    { id: 'tx-wilco', state: 'Texas', county: 'Williamson County' },
    { id: 'tx-wise', state: 'Texas', county: 'Wise County' },
    { id: 'tx-wood', state: 'Texas', county: 'Wood County' },
    { id: 'ut-dcso', state: 'Utah', county: 'Davis County' },
    { id: 'ut-slcs', state: 'Utah', county: 'Salt Lake County' },
    { id: 'ut-scso', state: 'Utah', county: 'Sanpete County' },
    { id: 'ut-utah', state: 'Utah', county: 'Utah County Corrections Bureau' },
    { id: 'ut-wcso', state: 'Utah', county: 'Weber County' },
    { id: 'va-acso', state: 'Virginia', county: 'Accomack County' },
    { id: 'va-abso', state: 'Virginia', county: 'Albemarle County' },
    { id: 'va-alsd', state: 'Virginia', county: 'Alleghany County' },
    { id: 'va-acsd', state: 'Virginia', county: 'Augusta County' },
    { id: 'va-brrjh', state: 'Virginia', county: 'Blue Ridge Regional, Halifax' },
    { id: 'va-bcso', state: 'Virginia', county: 'Botetourt County' },
    { id: 'va-bso', state: 'Virginia', county: 'Bristol' },
    { id: 'va-cvrj', state: 'Virginia', county: 'Central Virginia Regional' },
    { id: 'va-wcj', state: 'Virginia', county: 'Charlotte County' },
    { id: 'va-cpso', state: 'Virginia', county: 'City of Portsmouth' },
    { id: 'va-cwccso', state: 'Virginia', county: 'City of Williamsburg' },
    { id: 'va-ccso', state: 'Virginia', county: 'Culpeper County' },
    { id: 'va-dcso', state: 'Virginia', county: 'Danville County' },
    { id: 'va-fair', state: 'Virginia', county: 'Fairfax County' },
    { id: 'va-fcso', state: 'Virginia', county: 'Franklin County' },
    { id: 'va-hcj', state: 'Virginia', county: 'Hampton City' },
    { id: 'va-hcsd', state: 'Virginia', county: 'Henry County' },
    { id: 'va-lcadc', state: 'Virginia', county: 'Loudoun County' },
    { id: 'va-mrso', state: 'Virginia', county: 'Martinsville County' },
    { id: 'va-mrrj', state: 'Virginia', county: 'Meherrin River Regional' },
    { id: 'va-mprsc', state: 'Virginia', county: 'Middle Peninsula' },
    { id: 'va-mcso', state: 'Virginia', county: 'Montgomery County' },
    { id: 'va-nrvrj', state: 'Virginia', county: 'New River Valley Regional' },
    { id: 'va-nncj', state: 'Virginia', county: 'Newport News City' },
    { id: 'va-nrflk', state: 'Virginia', county: 'Norfolk County' },
    { id: 'va-ncso', state: 'Virginia', county: 'Northampton County' },
    { id: 'va-nnrj', state: 'Virginia', county: 'Northern Neck Regional' },
    { id: 'va-nradc', state: 'Virginia', county: 'Northwest Regional Adult' },
    { id: 'va-pgso', state: 'Virginia', county: 'Page County' },
    { id: 'va-pjms', state: 'Virginia', county: 'Pamunkey Regional' },
    { id: 'va-pcso', state: 'Virginia', county: 'Patrick County' },
    { id: 'va-pgcj', state: 'Virginia', county: 'Petersburg City' },
    { id: 'va-prj', state: 'Virginia', county: 'Piedmont Regional' },
    { id: 'va-ptso', state: 'Virginia', county: 'Pittsylvania County' },
    { id: 'va-pcj', state: 'Virginia', county: 'Portsmouth City' },
    { id: 'va-pwcso', state: 'Virginia', county: 'Prince William County' },
    { id: 'va-rrj', state: 'Virginia', county: 'Riverside Regional' },
    { id: 'va-rnso', state: 'Virginia', county: 'Roanoke City' },
    { id: 'va-rcso', state: 'Virginia', county: 'Rockbridge County' },
    { id: 'va-rcj', state: 'Virginia', county: 'Rockingham Regional' },
    { id: 'va-shcj', state: 'Virginia', county: 'Southampton County' },
    { id: 'va-srj', state: 'Virginia', county: 'Southside Regional' },
    { id: 'va-scsor', state: 'Virginia', county: 'Stafford County' },
    { id: 'va-scsd', state: 'Virginia', county: 'Sussex County' },
    { id: 'va-vbso', state: 'Virginia', county: 'Virginia Beach' },
    { id: 'va-wtrj', state: 'Virginia', county: 'Western Tidewater Regional' },
    { id: 'va-wvrj', state: 'Virginia', county: 'Western Virginia Regional' },
    { id: 'wa-cc', state: 'Washington', county: 'Clark County' },
    { id: 'wa-ccso', state: 'Washington', county: 'Cowlitz County' },
    { id: 'wa-kc', state: 'Washington', county: 'King County' },
    { id: 'wa-lcso', state: 'Washington', county: 'Lincoln County' },
    { id: 'wa-lwso', state: 'Washington', county: 'Lynnwood County' },
    { id: 'wa-mcso', state: 'Washington', county: 'Marysville County' },
    { id: 'wa-pcj', state: 'Washington', county: 'Pierce County' },
    { id: 'wa-skag', state: 'Washington', county: 'Skagit County' },
    { id: 'wa-scso', state: 'Washington', county: 'Snohomish County' },
    { id: 'wa-spso', state: 'Washington', county: 'Spokane County' },
    { id: 'wa-tcso', state: 'Washington', county: 'Thurston County' },
    { id: 'wa-wcso', state: 'Washington', county: 'Whatcom County' },
    { id: 'wv-rj', state: 'West Virginia', county: 'West Virginia Regional' },
    { id: 'wi-barr', state: 'Wisconsin', county: 'Barron County' },
    { id: 'wi-bcso', state: 'Wisconsin', county: 'Buffalo County' },
    { id: 'wi-dcso', state: 'Wisconsin', county: 'Douglas County' },
    { id: 'wi-jcsd', state: 'Wisconsin', county: 'Jefferson County' },
    { id: 'wi-knsh', state: 'Wisconsin', county: 'Kenosha County' },
    { id: 'wi-lcsd', state: 'Wisconsin', county: 'La Crosse County' },
    { id: 'wi-mcs', state: 'Wisconsin', county: 'Milwaukee County' },
    { id: 'wi-pcj', state: 'Wisconsin', county: 'Pierce County' },
    { id: 'wi-pcs', state: 'Wisconsin', county: 'Polk County' },
    { id: 'wi-rcs', state: 'Wisconsin', county: 'Racine County' },
    { id: 'wi-wcsd', state: 'Wisconsin', county: 'Wood County' },
    { id: 'wy-scso', state: 'Wyoming', county: 'Sweetwater County' },
    { id: 'wy-tcso', state: 'Wyoming', county: 'Teton County' }
]